### ISSUE TITLE
new release with latest changes?

### ISSUE THREAD

**Issue by jneilliii** [greghesp/pybambu#7]
could we please get a release that has the python <3.10 changes published to pypi? I know this repo has been updated but no new updates on pypi for referencing in requirements yet.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/pybambu/releases/tag/1.0.1

Note that I'm planning to clean this up and add properties so that no usage requires reaching in to use class members directly - everything will be marked as private (_ prefix) as part of that breaking change.

**Comment by jneilliii** [comment]
thanks for the heads up and release
